import mongoose from "mongoose";

const withdrawalSchema = new mongoose.Schema(
  {
    vendorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Vendor",
      required: true,
      index: true,
    },
    walletId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Wallet",
      required: true,
    },
    requestedAmount: {
      type: Number,
      required: true,           // What the vendor asked to withdraw
    },
    transferFee: {
      type: Number,
      default: 0,               // Paystack transfer fee (NGN 100 / NGN 200 / NGN 300)
    },
    netAmount: {
      type: Number,
      required: true,           // requestedAmount - transferFee (what actually hits their account)
    },
    status: {
      type: String,
      enum: ["pending", "processing", "completed", "failed", "reversed"],
      default: "pending",
      index: true,
    },
    paystackReference: {
      type: String,
      unique: true,
      required: true,           // UUID generated by us — used as idempotency key with Paystack
    },
    paystackTransferCode: {
      type: String,
      default: null,            // Returned by Paystack after transfer initiation e.g. "TRF_xxxx"
    },
    recipientCode: {
      type: String,
      required: true,           // Paystack recipient_code used for this transfer
    },
    bankName: { type: String, default: "" },
    accountNumber: { type: String, default: "" },
    accountName: { type: String, default: "" },
    failureReason: {
      type: String,
      default: null,            // Populated from Paystack webhook on failure
    },
    initiatedAt: {
      type: Date,
      default: Date.now,
    },
    settledAt: {
      type: Date,
      default: null,            // Populated when transfer.success webhook fires
    },
    walletDebitedAt: { type: Date, default: null },
    retryOf: { type: mongoose.Schema.Types.ObjectId, ref: "Withdrawal", unique: true, sparse: true },
    activePayoutKey: { type: String, unique: true, sparse: true },
    fundsRestoredAt: { type: Date, default: null },
    lastVerifiedAt: { type: Date, default: null },
    providerStatus: { type: String, default: null },
    providerFailureReason: { type: String, default: null },
    providerTransferredAt: { type: Date, default: null },
    reconciliationStatus: { type: String, enum: ["unverified", "matched", "status_mismatch", "amount_mismatch", "manual_review"], default: "unverified", index: true },
    reconciliationAttempts: { type: Number, default: 0 },
    lastProviderPayload: { type: mongoose.Schema.Types.Mixed, default: null },
    reconciliationHistory: [{ source: String, localStatus: String, providerStatus: String, outcome: String, at: { type: Date, default: Date.now } }],
  },
  { timestamps: true }
);

// Compound index: fast lookup by vendor + status for dashboard queries
withdrawalSchema.index({ vendorId: 1, status: 1 });

export default mongoose.model("Withdrawal", withdrawalSchema);
